# Generated by Django 4.0.5 on 2022-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourseapp', '0002_gallery_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_img1', models.ImageField(upload_to='images')),
                ('icon_img2', models.ImageField(upload_to='images')),
            ],
        ),
    ]
