# Generated by Django 4.0.5 on 2022-06-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('onlinecourseapp', '0005_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link1', models.ImageField(upload_to='images')),
                ('link2', models.ImageField(upload_to='images')),
                ('home_img', models.ImageField(upload_to='images')),
                ('about_img', models.ImageField(upload_to='images')),
                ('gallery_img1', models.ImageField(upload_to='images')),
                ('gallery_img2', models.ImageField(upload_to='images')),
                ('gallery_img3', models.ImageField(upload_to='images')),
                ('gallery_img4', models.ImageField(upload_to='images')),
                ('gallery_img5', models.ImageField(upload_to='images')),
                ('gallery_img6', models.ImageField(upload_to='images')),
                ('blog_img1', models.ImageField(upload_to='images')),
                ('blog_name1', models.IntegerField()),
                ('blog_name2', models.CharField(max_length=10)),
                ('team_img1', models.ImageField(upload_to='images')),
                ('team_img2', models.ImageField(upload_to='images')),
                ('team_img3', models.ImageField(upload_to='images')),
                ('team_img4', models.ImageField(upload_to='images')),
                ('footer_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
